[package]
name = "jira-lens"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
slint = { version = "1.17.1", default-features = false, features = ["std", "backend-winit", "renderer-femtovg", "compat-1-2"] }

[build-dependencies]
slint-build = "1.17.1"

[profile.release]
lto = "thin"
strip = true
codegen-units = 1

